import { Protein } from 'src/app/views/proteins/interfaces/protein-info.interface';

export class ProteinData {
  static protein: Protein[] = [
    {
      accession: 'O43657',
      protein: 'Tetraspanin-6',
      gene: 'TSPAN6',
      sequence:
        'MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSLENYFSLLNEKATNVPFVLIATGTVIILLGTFGCFATCRASAWMLKLYAMFLTLVFLVELVAAIVGFVFRHEIKNSFKNNYEKALKQYNSTGDYRSHAVDKIQNTLHCCGVTDYRDWTDTNYYSEKGFPKSCCKLEDCTPQRDADKVNNEGCFIKVMTIIESEMGVVAGISFGVACFQLIGIFLAYCLSRAITNNQYEIV',
    },
  ];
}
